"use client";
import "./normalize.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import DefaultTheme from "@/theme/theme";
import { NoSsr } from "@mui/material";

 const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (  
    <ThemeProvider theme={DefaultTheme}>
      <html lang="en">
        <CssBaseline />
        <body className={inter.className}>{children}</body> 
      </html>   
    </ThemeProvider>
    
  );
}
